# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  workflow_call:
    inputs:
      FILENAME:
        required: true
        type: string
      SCHEME:
        required: false
        default: DemoApp
        type: string
      CONFIGURATION:
        required: false
        default: Debug
        type: string
      DESTINATION:
        required: false
        default: 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
        type: string

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
            FILENAME_AND_EXTENSION=$(basename -- "${{ inputs.FILENAME }}")
            ONLY_FILENAME="${FILENAME_AND_EXTENSION%.*}"

            xcodebuild -workspace "${{ inputs.FILENAME }}" \
                -derivedDataPath docsData \
                -scheme "${{ inputs.SCHEME }}" \
                -destination "${{ inputs.DESTINATION }}" \
                -parallelizeTargets docbuild

            cp -R `find docsData -type d -name '*.doccarchive'` .

            $(xcrun --find docc) process-archive transform-for-static-hosting \
                "${ONLY_FILENAME}".doccarchive \
                --hosting-base-path "${ONLY_FILENAME}"-iOS \
                --output-path docs

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs folder
          path: 'docs'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
