name: Check for Sign Off

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  sign-off-check:
    name: Check sign-off
    runs-on: ubuntu-latest
    steps:
      - name: sign off
        uses: krogertechnology/sign-off@v1.0.1
        with:
          github-token: ${{ secrets.github-token }}